import { App } from 'aws-cdk-lib';
import { Template } from 'aws-cdk-lib/assertions';
import { NdxStaticStack } from '../lib/ndx-stack';

// Validates: Complete CloudFormation template integrity
// Why: Catches ANY unintended infrastructure changes (FR31)
// This snapshot test captures the entire CloudFormation template generated by CDK,
// enabling automatic detection of any unintended modifications to the infrastructure.
describe('NdxStaticStack', () => {
  test('CloudFront configuration snapshot', () => {
    const app = new App();
    const stack = new NdxStaticStack(app, 'TestStack');
    const template = Template.fromStack(stack);

    // Snapshot captures entire CloudFormation template
    // Including: Distribution, Function, CachePolicy, Origins, OAC
    expect(template.toJSON()).toMatchSnapshot();
  });
});
